# Generated by Django 3.1.1 on 2020-11-05 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='Заголовок')),
                ('slug', models.SlugField(default='', max_length=64, unique=True)),
                ('author', models.CharField(max_length=24, verbose_name='Автор')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Имя')),
                ('username', models.CharField(max_length=24, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(default='', max_length=256, unique=True, verbose_name='Почта')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('hash_pasword', models.CharField(max_length=32, verbose_name='Hash пароль')),
                ('registered_at', models.DateTimeField(auto_now=True, verbose_name='Зарегистрирован')),
                ('banned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['registered_at'],
            },
        ),
    ]
