# Generated by Django 3.1.3 on 2020-12-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201221_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='raiting',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rate_count',
        ),
    ]
