# Generated by Django 3.1.1 on 2020-11-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201105_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='rate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
    ]
