# Generated by Django 3.1.3 on 2020-12-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201223_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='Заголовок')),
                ('slug', models.SlugField(default='', max_length=126, unique=True)),
                ('raiting', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=24, verbose_name='Автор')),
                ('discussion', models.JSONField(blank=True, verbose_name='Дискусия')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
    ]
