# Generated by Django 3.1.3 on 2020-12-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='discussion',
        ),
        migrations.AddField(
            model_name='post',
            name='answers',
            field=models.JSONField(default=dict, verbose_name='Ответы'),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(max_length=20, null=True, verbose_name='Заголовок'),
        ),
    ]
