# Generated by Django 3.1.3 on 2020-12-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201224_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Заголовок'),
        ),
    ]
