# Generated by Django 3.1.3 on 2020-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201224_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answers',
            field=models.JSONField(default=dict, null=True, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Тип'),
        ),
    ]
