# Generated by Django 3.1.3 on 2020-12-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201226_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ответы'),
        ),
    ]
