# Generated by Django 3.1.3 on 2021-01-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_rated_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rated_posts',
        ),
        migrations.AddField(
            model_name='article',
            name='rated',
            field=models.JSONField(blank=True, default=dict, verbose_name='Поставленные оценки'),
        ),
    ]
