# Generated by Django 3.1.3 on 2021-01-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210130_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Комментарии'),
        ),
    ]
