# Generated by Django 3.1.3 on 2021-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210131_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.JSONField(default=dict, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.JSONField(default=dict, verbose_name='Комментарии'),
        ),
    ]
