# Generated by Django 3.1.3 on 2021-02-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210131_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
